version: '2'

volumes:
  x11:

services:
  ffplay:
    build: .
    privileged: true
    environment:
      RTSP_URI:
      CURSOR: "false"
    devices:
      - /dev/dri
    group_add:
      - video
    volumes:
      - 'x11:/tmp/.X11-unix'
    depends_on:
      - xserver
  xserver:
    image: balenablocks/xserver
    restart: always
    privileged: true
    volumes:
      - 'x11:/tmp/.X11-unix'